---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lemmy
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  rules:
  - host: 10.0.0.1.xip.io
    http:
      paths:
      - backend:
          service:
            name: lemmy-nginx
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - ""

