---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lemmy
  - lemmy-ui
  - pictrs
  - nginx
  - ./ingress.yaml
commonLabels:
  app.kubernetes.io/service: lemmy
  app.kubernetes.io/managed-by: Kustomize
images:
- name: docker.io/dessalines/lemmy:0.17.4
  newTag: "0.18.0-rc.8"
- name: docker.io/dessalines/lemmy-ui:0.17.4
  newTag: "0.18.0-rc.8"
replacements:
- source:
    kind: Service
    name: lemmy
  targets:
  - select:
      kind: Deployment
      name: lemmy-ui
    fieldPaths:
      - spec.template.spec.containers.*.env.[name=LEMMY_UI_LEMMY_INTERNAL_HOST].value
    options:
      delimiter: ':'
      index: 0
