---
apiVersion: v1
kind: Service
metadata:
  name: pictrs
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: pictrs
    app.kubernetes.io/name: pictrs
  type: ClusterIP

