---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lemmy-nginx-conf
data:
  01-lemmy.conf.template: |
    server {
        listen 8080;
        server_name localhost;
        access_log /dev/stdout json_logs;
        server_tokens off;
        resolver ${DNS_RESOLVER_SERVICE}.${DNS_RESOLVER_NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN};
        gzip on;
        gzip_types text/css application/javascript image/svg+xml;
        gzip_vary on;
        client_max_body_size 20M;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        location / {
            set $proxpass "http://lemmy-ui.federation.svc.cluster.local:1234";
            if ($http_accept = "application/activity+json") {
              set $proxpass "http://lemmy.${NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN}:8536";
            }
            if ($http_accept = "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"") {
              set $proxpass "http://lemmy.${NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN}:8536";
            }
            if ($request_method = POST) {
              set $proxpass "http://lemmy.${NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN}:8536";
            }
            proxy_pass $proxpass;
            rewrite ^(.+)/+$ $1 permanent;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location ~ ^/(api|pictrs|feeds|nodeinfo|.well-known) {
            resolver ${DNS_RESOLVER_SERVICE}.${DNS_RESOLVER_NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN};
            proxy_pass "http://lemmy.${NAMESPACE}.svc.${DNS_RESOLVER_DOMAIN}:8536";
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
  nginx.conf: |
      worker_processes  auto;
      pid        /tmp/nginx.pid;
      events {
          worker_connections  1024;
      }
      http {
          proxy_temp_path /tmp/proxy_temp;
          client_body_temp_path /tmp/client_temp;
          fastcgi_temp_path /tmp/fastcgi_temp;
          uwsgi_temp_path /tmp/uwsgi_temp;
          scgi_temp_path /tmp/scgi_temp;
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;
          log_format json_logs escape=json
            '{'
              '"remote_addr":"$remote_addr",'
              '"http_x_forwarded_for":"$http_x_forwarded_for",'
              '"time_local":"$time_local",'
              '"status": "$status",'
              '"request":"$request",'
              '"http_referrer":"$http_referer",'
              '"http_user_agent":"$http_user_agent"'
            '}';
          access_log /var/log/nginx/access.log json_logs;
          error_log  /var/log/nginx/error.log notice;
          sendfile        on;
          keepalive_timeout  65;
          include /etc/nginx/conf.d/*.conf;
      }

