---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "lemmy-nginx-conf"
  name: lemmy-nginx
spec:
  replicas: 2
  selector:
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: nginx
          image: "ghcr.io/nginxinc/nginx-unprivileged:1.25-alpine"
          imagePullPolicy: IfNotPresent
          env:
            - name: DNS_RESOLVER_SERVICE
              value: kube-dns
            - name: DNS_RESOLVER_NAMESPACE
              value: kube-system
            - name: DNS_RESOLVER_DOMAIN
              value: cluster.local
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              cpu: 20m
              memory: 128Mi
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/nginx/templates/01-lemmy.conf.template
              readOnly: true
              name: nginx-conf
              subPath: 01-lemmy.conf.template
            - mountPath: /etc/nginx/nginx.conf
              readOnly: true
              name: nginx-conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: lemmy-nginx-conf
