---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - config-map.yaml
commonLabels:
  app.kubernetes.io/name: lemmy-nginx
  app.kubernetes.io/component: lemmy-nginx
