apiVersion: v1
kind: Service
metadata:
  name: lemmy
  labels:
    app.kubernetes.io/component: lemmy
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8536
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: lemmy
    app.kubernetes.io/name: lemmy
  type: ClusterIP

