---
name: "Publish OCI Manifests on Release"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  packages: write
  id-token: write

env:
  OCI_REPO: "oci://ghcr.io/anthr76/${{ github.event.repository.name }}"

jobs:
  publish-oci:
    name: Publish OCI on release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.0.0-rc.5
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push manifests
        run: |
          digest_url=$(flux push artifact \
          $OCI_REPO:$(git rev-parse --short HEAD) \
          --path="./" \
          --source="$(git config --get remote.origin.url)" \
          --revision="$(git tag --points-at HEAD)/$(git rev-parse HEAD)"
          jq -r '. | .repository + .digest')

          flux tag artifact $OCI_REPO:$(git rev-parse --short HEAD) --tag "$(git tag --points-at HEAD)"

          echo $digest_url
